### ISSUE TITLE
Sizing issue 

### ISSUE THREAD

**Issue by dreamBegin** [dkun7944/perfect-pitch-ios#1]
Hey daniel,

Your project is really cool and it helps me out really well but one thing to ask how did you deal with the size of the audiokit , i also checked out your pitch tuner on the app store congrats for that, great app. if i include audiokit explicitly in a new project and make a build the size of the framework in .app will be 64mb apprx and after enabling the  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES the size of the framework increased to 86mb any help with that.

thanks in advance
-kuldeep

**Comment by dkun7944** [comment]
Hey kuldeep,

Have you tried cocoapods?

**Comment by dreamBegin** [comment]
Thanks for the reply Daniel,

Actually i tried both way Using Cocoapods and including it explictly but not going well, one thing to be considered that I'm using Objective-C and the framework is written in swift. which way do you prefer I use cocoapods or by including it explictly?

**Comment by dkun7944** [comment]
I use cocoapods for all AudioKit enabled projects. Just using the standard settings in Xcode with Swift 3. Maybe you should open an issue on the [AudioKit Github. ](https://github.com/audiokit/AudioKit/issues)

**Comment by dreamBegin** [comment]
did your app size was same before uploading the app to appstore i'm getting suggestions about bitcode and i already opened the issue [here](https://github.com/audiokit/AudioKit/issues/758) but didn't get the solution maybe i need to search a bit more.

**Comment by dkun7944** [comment]
[Check out this thread](https://github.com/ReactiveX/RxSwift/issues/1067)

Not AudioKit but the same principles apply.

**Comment by dreamBegin** [comment]
Great man , thanks for the help. I owe you , once again thanks for all the time.will work on that, Cheers 💯 .

**Comment by dkun7944** [comment]
No prob!
